on:
  schedule:
    - cron: '57 22 * * *'
  workflow_dispatch:

# These are the magic lines that fix the "id-token" and 404 issues
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  scrape_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install requests beautifulsoup4

      - name: Run Preston Scraper
        env:
          FUEL_CLIENT_ID: ${{ secrets.FUEL_CLIENT_ID }}
          FUEL_CLIENT_SECRET: ${{ secrets.FUEL_CLIENT_SECRET }}
        run: python scraper.py

      # This creates the package GitHub Pages needs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # This actually publishes the site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
